onedrive:
  clientId: 09939809-c617-43c8-a220-a93c1513c5d4
  clientSecret: _l:zI-_yrW75lV8M61K@z.I2K@B/On6Q
  redirectUri: http://119.23.60.193:9999/onedrive/callback
  scope: offline_access User.Read Files.ReadWrite.All
  authenticateUrl: https://login.microsoftonline.com/common/oauth2/v2.0/token

server:
  port: 9999
spring:
  application:
    name: JavaRun
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: /**
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: templates
  mvc:
    static-path-pattern: static/**