onedrive:
  clientId: 6d027ece-1899-4c3e-8239-6eae511f0964
  clientSecret: hSf7Q~CKP5pT8HHX_WGAhzCmxOU4JSYfJ3l2y
  redirectUri: https://api.rawchen.com/onedrive/callback
  scope: offline_access User.Read Files.ReadWrite.All
  authenticateUrl: https://login.microsoftonline.com/common/oauth2/v2.0/token

server:
  port: 9999
spring:
  application:
    name: JavaRun
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: /**
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  # 配置 smtp 服务器地址
  mail:
    host: smtp.qq.com
    # smtp 服务器的端口
    port: 587
    # 根据自己的邮箱配置账号以及授权码
    username: 2221999792@qq.com
    password: kxukqpqieowkxxxx
    default-encoding: UTF-8
    properties:
      from: 2221999792@qq.com
  mvc:
    static-path-pattern: static/**

logging:
  level:
    org.apache.coyote.http11.Http11Processor: warn